import logging
from langgraph.graph import END

from pydantic import TypeAdapter
from pydantic_core import ValidationError
from textwrap import dedent
from app.domain.state import CheckResult, HumanAdvicePayload, SkillSuggestion, State, ToolDecisionPayload
from langgraph.types import Command

from app.nodes.utils import get_prompt_subfix

logger = logging.getLogger(__name__)


def diagnosis_node(llm):
    def node(state: State) -> Command:
        '''Agent node to analyze the collected information and provide a diagnosis or analysis result.
        This node will use the LLM to synthesize the information gathered from the logs, git repository, and service description to generate insights, identify potential causes of issues, and suggest next steps for resolution.
        '''
        prompt = dedent(f"""{get_prompt_subfix(state)}
        
        Secrets comparison:
        - Service secrets: {state.secrets_info.service_on_analysis_secrets}
        - Reference services secrets: {state.secrets_info.reference_service_secrets}
        
        Your task is to identify the root causes of the errors shown in the Error Logs above.
        Compare the service secrets against the reference secrets, focusing only on fields relevant to the error (e.g., if the error is database-related, compare DB credentials, endpoints, and names).
        
        Rules:
        - Do NOT invent causes, only identify causes directly supported by the evidence.
        - Return exactly the top 3 most likely causes, ordered by confidence (0-100).
        - Each cause must be directly supported by evidence in the error logs, recent file changes, or secrets mismatch.
        - Exclude causes related to network infrastructure (DNS, NAT, VPC, ACLs, etc.).
        - Be concrete and specific — vague or speculative causes are not useful.
        
        Respond ONLY with a Markdown text with this exact format:
        
        | Potential Cause | Confidence Level (0-100) |
        |-----------------|-------------------------|
        | <concise description> | <0-100> |
        
        
        Return an empty table if the error logs lack sufficient information for a diagnosis.
        """)

        msg = llm.invoke(prompt)
        return Command(update={'analysis_result': msg.content})
    return node


def diagnosis_check_node(llm):
    def node(state: State) -> Command:
        ''' Agent node to analyze the diagnosis result and determine if further analysis is needed.
        This node will evaluate the analysis result generated by the diagnosis_node to determine if the confidence 
        levels of the potential causes are sufficient to proceed with resolution, or if additional information 
        gathering and analysis is required before making a decision on next steps.
        '''
        
        prompt = dedent(f"""{get_prompt_subfix(state)}
        
        ### Your task:
        Based on the following analysis result, determine if the confidence levels of the potential causes are 
        sufficient to proceed with resolution (At least one with more than 75% confidence and a credible potential cause).
        
        Also check that the analysis result is well founded and not based on speculative or vague causes. 
        If the analysis result is not well founded, even if it has high confidence levels, you should recommend to gather more information and perform a deeper analysis before proceeding with any resolution.
        
        ### Analysis Result:
        {state.analysis_result}
        
        ### Output format:
        Respond with a JSON that provides a justification for your decision. Follow this answer JSON format strictly:
        
        {{
            "proceed": true or false,
            "justification": "<your justification for the decision>"
        }}
        """)

        msg = llm.invoke(prompt)
        try:
            result = CheckResult.model_validate_json(msg.content)
            return Command(update={'analysis_check_result': result.model_dump()})
        except ValidationError:
            logger.error(f"Error processing diagnosis check result: Invalid response format. Response was: {msg.content}")
            return Command(update={'analysis_check_result': {'justification': 'Invalid response format', 'proceed': False}})
    return node


def skills_suggestion_node(llm):
    def node(state: State) -> Command:
        ''' Agent node to suggest which skills to use based on the diagnosis and analysis results.
        This node will analyze the diagnosis and analysis results to recommend specific skills or tools that could be effective in addressing the identified issues, providing guidance on how to proceed with remediation.
        '''
        prompt = dedent(f"""{get_prompt_subfix(state)}
                        
        ### Your task:
        Based on the diagnosis and analysis results, suggest which skills or tools would be the most effective for addressing the identified issues. 
        Provide a Justification for each suggested skill, explaining how it relates to the potential causes and why it would be useful for remediation.
        If no skills are relevant, respond that no skills are suggested and focus on providing a remediation plan without mentioning skills.
        
        ### Diagnosis and Analysis Summary:
        
        #### Diagnosed potential causes (from prior analysis):
        {state.analysis_result}
        #### Skills catalog:
        | Skill Name | Description |
        |------------|-------------|
        {"\n".join([f"| {skill} | {details.get('description', '')} |" for skill, details in state.skills_catalog.items()])}
        
        ### Output format:
        Respond with a JSON based this exact format (If not skills are relevant, respond with an empty array []):
        
        [
            {{
                "name": "<the skill name from the catalog>",
                "description": "<repeat the description of the skill>",
                "justification": "<brief explanation of why this skill is relevant>"
            }},
            ...
        ]
              
        """)

        msg = llm.invoke(prompt)
        try:
            adapter = TypeAdapter(list[SkillSuggestion])
            result = adapter.validate_json(msg.content)
            return Command(update={'skills_suggestion': [r.model_dump() for r in result]})
        except ValidationError:
            logger.error(f"Error processing skills suggestion: Invalid response format. Response was: {msg.content}")
            return Command(update={'error_message': 'Error processing skills suggestion: Invalid response format'}, goto=END)
    return node


def remediation_node(llm):
    def node(state: State) -> Command:
        ''' Agent node to provide remediation steps based on the diagnosis and analysis check results.
        This node will use the LLM to generate actionable remediation steps based on the diagnosis provided 
        by the diagnosis_node and the decision made in the diagnosis_check_node, 
        guiding the user towards resolving the identified issues.
        '''
        prompt = dedent(f"""You are the DevOps engineer responsible for the service "{state.context.service_name}".
        
        {get_prompt_subfix(state)}
        
        ### Secrets comparison:
        - Service secrets: {state.secrets_info.service_on_analysis_secrets}
        - Reference services secrets: {state.secrets_info.reference_service_secrets}
        
        ### Diagnosed potential causes (from prior analysis):
        {state.analysis_result}
        
        ### Skills suggestion:
        {state.skills_suggestion}
        
        ---
        
        Your task is to provide a concrete remediation plan for the causes listed above.
        
        ### Rules:
        - Do NOT invent causes or sugestions, only identify causes directly supported by the evidence.
        - Be clear and explicit on your remediation advice, avoid vague or generic suggestions. If you talk about use any value or solution just name it.
        - Prioritize the cause with higher confidence, if the higher confidence is below 75%, consider other potential causes.
        - If a cause references a specific file or component, include it in the remediation solution.
        - Consider recent file changes as potential contributors.
        - Focus on: codebase fixes, application/framework configuration, AWS component connections, and software design.
        - Do NOT suggest network-level remediations (DNS, NAT, VPC, ACLs) unless the service were a kind of apiGateway.
        - If secrets mismatches are identified as potential causes, include it (and the values) to verify and correct relevant secrets. You can also sugest Reference services secrets-similar values (reference services supposed to share similar secrets). This is important in order to fix misconfigurations that could be causing the issue.
        - Use the following Common troubleshooting actions guide to complement your advice:
            - For api gateway services:
                - If there are error connecting or resolving some service or ui the common reason is missing or wrong gateway routing rule. In order to resolve it, does:
                - Check the current configured routes through the endpoint GET /api-gw/routes
                - If the endpoint exists proceed to check if the uri (commonly maped against a k82 service pod) is well configured.
                - If the uri is well configured proceed to check if the service is up and running hitting the desired service healcheck endpoint /actuator/health
            - For regular application services:
                - If there are conection with external infra component (database, cache, etc) issues you should check the following:
                - Check that environment variables are correctly configured in the vault secret manager, and that the values are correct.
                - Check that the external component is up and running.
            - If you need to check system env values, refer the AWS sercret manager where the envs are stored, and check if the values are correct. You can also check the env values on the application.yml file, but remember that the values on the application.yml file are only for local development, in production the values are loaded from the vault secret manager.
            - Notes:
                - Avoid if to modify routes using DynamoDB directly, as this can lead to inconsistencies and potential issues with the application. Always prefer using the API REST for managing routes, as it ensures that changes are properly validated and applied without risking the integrity of the routing configuration.
        - Based on the skills preliminar suggestion, suggest the skills that fits better in order to solve the issue (read carefully the skills descriptions). If no skills are relevant, just provide the remediation steps without mentioning the skills.
        ---
        
        
        Respond with ONLY with a consise remediation fix (or sugestion) in one phrase and the skills that could be used to automate it (if apply). Taking in account that someone with full knowledge of the system will read your advice. Fucus on the main problem and give a direct and actionable advice. No preamble, no verbose explanations — just the remediation.
        One remediation by potential diagnosed couse, if you have multiple potential causes, prioritize the remediation for the one with higher confidence. Add a section with sugestion for other potential causes if you have more than one, but keep it concise and focused on the main issue. If the confidence level of all potential causes is low, provide a remediation that focuses on gathering more information or improving monitoring to get better insights into the issue.
        
        ### IMPORTANT:
        - Allways hide passwords or sensitive information in the remediation steps. If the remediation involves verifying or correcting secrets, refer to them as a key without exposing actual secret values.
        - Don't forget to suggest the relevant skills (if apply) from the skills catalog that could be used to automate the remediation steps, this is a crucial part of the remediation advice.
        - Output formatting rules:
            - Code whith simple ticks or triple ticks: should be enclosed by <pre> tags to preserve formatting in Telegram messages.
            - Bold important details using <b> tags to make them stand out in Telegram messages.
            - Use new lines to separate different remediation steps or suggestions for clarity in Telegram messages.
            - If skills are sugested, ask to the user if they want to automate the remediation using the suggested skills. Use a phrase like "Do you want to proceed with the remediation using the suggested skills?". Put this allways at the end of the full message.
        """)

        msg = llm.invoke(prompt)
        return Command(update={'remediation_steps_suggestion': msg.content})
    return node


def human_advice_processor_node(llm):
    def node(state: State) -> Command:
        ''' 
        Agent for processing human advice and integrating it into the workflow.
        This node will take the advice provided by a human user, analyze it in 
        the context of the diagnosis and analysis results, and determine how to incorporate that advice into the remediation plan or next steps for resolving the identified issues.
        '''
        prompt = dedent(f"""
        Analyze the following user message and determine the intended action.

        The message may be written in Spanish or English.

        Possible decisions:
        - Proceed → the user wants to continue or approves the process
        - Dismiss → the user wants to cancel, reject, or stop

        Additionally, the user may:
        1. Suggest tools to use
        2. Provide general guidance or instructions in natural language

        Available tools (ONLY these are allowed to be adviced, do NOT suggest any tool not in this list):
        {state.skills_catalog}

        Instructions:
        - Do NOT invent tools
        - Only include tools explicitly mentioned by the user and tools sugested
        - Ignore tools not in the allowed list
        - If the user provides suggestions or guidance, the decision should be Proceed
        - Interpret intent semantically, not literally
        - If the intent is unclear, default to Dismiss

        Suggestions handling:
        - Extract any user guidance, instructions, or preferences as plain text
        - Do NOT convert suggestions into tools
        - Do NOT invent or expand suggestions
        - If no suggestions are present, return an empty string

        Examples:
        - "yes, go ahead" → Proceed
        - "sí, pero usa tool_a y hazlo rápido" → Proceed + tool_a + suggestion
        - "no, cancel this" → Dismiss
        - "usa tool_b pero con más detalle" → Proceed + tool_b + suggestion
        - "Adelante, ademas usa estas tools: tool_a, tool_c" → Proceed + tool_a + tool_c
        - "No, no quiero continuar" → Dismiss

        Respond ONLY in valid JSON:

        {{
            "decision": "Proceed | Dismiss",
            "tools": [],
            "suggestions": "",
            "confidence": 0.0-1.0
        }}

        The User message to be analyzed is:
        {state.human_chat_advice}
        
        > Remember to add the user message to the suggestions field in the output if the decision is Proceed, this will be used as an additional input for the remediation agent.
        """)

        msg = llm.invoke(prompt)
        try:
            result = HumanAdvicePayload.model_validate_json(msg.content)
            return Command(update={'human_advice_curated': result.model_dump()})
        except ValidationError:
            logger.error(f"Error processing human advice: Invalid response format. Response was: {msg.content}")
            return Command(update={'error_message': 'Error processing human advice: Invalid response format'}, goto=END)
    return node

def remediation_agent_executor_node(agent):
    async def node(state: State) -> Command:
        ''' Agent node to execute the remediation steps provided by the remediation node.
        This node will take the remediation steps suggested by the remediation_node and execute them using the appropriate skills or tools, aiming to resolve the identified issues based on the diagnosis and analysis results.
        '''
        result = await agent.ainvoke(state)
        last_message = result["messages"][-1]
        return Command(update={'final_message': last_message.content})
    return node
